# Generated by Django 4.2.14 on 2024-07-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtarizatsiya', '0002_usermodel_email_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationmodel',
            name='verify_type',
            field=models.CharField(choices=[('VIA_EMAIL', 'VIA_EMAIL'), ('VIA_PHONE', 'VIA_PHONE')], default='VIA_EMAIL', max_length=100),
        ),
    ]
